
class Endpoints:
    BASE = "https://valorant-api.com/v1/"
    Agents = BASE + "agents"
    Buddies = BASE + "buddies"
    Bundles = BASE + "bundles"
    Content_Tiers = BASE + "contenttiers"
    Currencies = BASE + "currencies"
    GameMode = BASE + "gamemodes"
    GamemodeEquippables = GameMode + "/equippables"
    Maps = BASE + "maps"
    PlayerCards = BASE + "playercards"
    PlayerTitles = BASE + "playertitles"
    Seasons = BASE + "seasons"
    Sprays = BASE + "sprays"
    Themes = BASE + "themes"
    Weapons = BASE + "weapons"
    Version = BASE + "version"
    CompetitiveTiers = BASE + "competitivetiers"
    Competitive = Seasons + "/competitive"
    WeaponSkins = Weapons + "/skins"
    WeaponSkinChromas = Weapons + "/skinchromas"
    WeaponSkinLevels = Weapons + "/skinlevels"
