class Endpoints:
    BASE = "https://valorant-api.com/v1/"
    Agents = BASE + "Agents"
    Buddies = BASE + "buddies"
    Bundles = BASE + "bundles"
    Content_Tiers = BASE + "contenttiers"
    Currencies = BASE + "currencies"
    GameMode = BASE + "gamemodes"
    GamemodeEquippables = BASE + "gamemodes/equippables"
    Maps = BASE + "maps"
    PlayerCards = BASE + "playercards"
    PlayerTitles = BASE + "playertitles"
    Seasons = BASE + "seasons"
    Themes = BASE + "themes"
    Weapons = BASE + "weapons"
    Version = BASE + "version"
